import { GoogleGenAI } from "@google/genai";

const apiKey = import.meta.env.VITE_GEMINI_API_KEY as string;

if (!apiKey) {
  console.warn("Missing VITE_GEMINI_API_KEY in your environment variables.");
}

const ai = new GoogleGenAI({ apiKey });

const RESTRICTED_WORDS = [
  "sex",
  "porn",
  "naked",
  "nude",
  "penis",
  "vagina",
  "breast",
  "ass",
  "butt",
  "pussy",
  "tukulane",
  "nitakudinya",
  "msolombo",
  "ngwati",
  "matako",
  "malaya",
  "nitakutusi"
] as const;

function containsRestrictedContent(input: string): boolean {
  const lower = input.toLowerCase();
  return RESTRICTED_WORDS.some((word) => lower.includes(word));
}

function buildFallbackFoodImage(mealCombo: string): string {
  return `https://picsum.photos/seed/${encodeURIComponent(mealCombo)}/800/800`;
}

function buildFallbackAvatar(fullname: string): string {
  return `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(fullname)}`;
}

function extractInlineImageData(response: unknown): string | null {
  const candidates =
    (response as {
      candidates?: Array<{
        content?: {
          parts?: Array<{
            inlineData?: { data?: string; mimeType?: string };
            text?: string;
          }>;
        };
      }>;
    }).candidates ?? [];

  for (const candidate of candidates) {
    const parts = candidate.content?.parts ?? [];
    for (const part of parts) {
      const base64 = part.inlineData?.data;
      const mimeType = part.inlineData?.mimeType ?? "image/png";

      if (base64) {
        return `data:${mimeType};base64,${base64}`;
      }
    }
  }

  return null;
}

function extractText(response: unknown): string | null {
  const typed = response as {
    text?: string;
    candidates?: Array<{
      content?: {
        parts?: Array<{ text?: string }>;
      };
    }>;
  };

  if (typeof typed.text === "string" && typed.text.trim()) {
    return typed.text.trim();
  }

  const candidates = typed.candidates ?? [];
  for (const candidate of candidates) {
    const parts = candidate.content?.parts ?? [];
    for (const part of parts) {
      if (typeof part.text === "string" && part.text.trim()) {
        return part.text.trim();
      }
    }
  }

  return null;
}

export async function generateMealImage(mealCombo: string): Promise<string> {
  if (!mealCombo.trim()) {
    throw new Error("Meal combo is required.");
  }

  if (containsRestrictedContent(mealCombo)) {
    throw new Error("INAPPROPRIATE_CONTENT");
  }

  try {

  function sanitizeMealCombo(mealCombo: string): string {
  return mealCombo
    .replace(/[^a-zA-Z0-9,\-\s]/g, "")
    .trim()
    .slice(0, 120);
}
    const safeMealCombo = sanitizeMealCombo(mealCombo);
    const response = await ai.models.generateContent({
     model: "gemini-3.1-flash-image-preview",
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `Generate an image of FOOD ONLY.

Subject: A Kenyan meal combo consisting strictly of: ${safeMealCombo}.

Hard requirements:
- Show only the prepared meal
- No people
- No hands
- No face
- No human body
- No animals
- No drinks unless explicitly mentioned in the meal combo
- No restaurant interior
- No background story elements
- No text
- No labels
- No watermark
- No extra objects unrelated to the meal

Style requirements:
- Realistic professional food photography
- Authentic Kenyan presentation
- Natural plating on a simple plate or bowl
- Clean plain background
- Bright appetizing lighting
- Sharp focus on the food
- Square composition

Output goal:
A realistic food app image showing only the exact meal mentioned, nothing else.`,
            },
          ],
        },
      ],
      config: {
        responseModalities: ["TEXT", "IMAGE"],
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    const imageData = extractInlineImageData(response);
    if (imageData) {
      return imageData;
    }

    const textResponse = extractText(response);
    if (textResponse) {
      console.warn("Model returned text instead of image:", textResponse);
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Error generating meal image:", error);
    return buildFallbackFoodImage(mealCombo);
  }
}

export async function generateProfileAvatar(fullname: string): Promise<string> {
  if (!fullname.trim()) {
    throw new Error("Full name is required.");
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `Create a clean, friendly, professional 3D student avatar for the name ${fullname}. Use a modern illustrated profile style, neutral background, polished lighting, and university-profile quality. No text.`,
            },
          ],
        },
      ],
      config: {
        responseModalities: ["TEXT", "IMAGE"],
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    const imageData = extractInlineImageData(response);
    if (imageData) {
      return imageData;
    }

    const textResponse = extractText(response);
    if (textResponse) {
      console.warn("Model returned text instead of avatar:", textResponse);
    }

    throw new Error("No avatar generated by the model.");
  } catch (error) {
    console.error("Error generating profile avatar:", error);
    return buildFallbackAvatar(fullname);
  }
}

export async function chatWithAssistant(
  message: string,
  context: string
): Promise<string> {
  if (!message.trim()) {
    return "Ask me about a meal combo, budget, or what to eat around campus.";
  }

  if (containsRestrictedContent(message)) {
    return "That request is not allowed here. This app is for student food discussions only.";
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: [
        {
          role: "user",
          parts: [
            {
              text: message,
            },
          ],
        },
      ],
      config: {
        systemInstruction: `You are the Ulikula? assistant for MMUST students.
Your goal is to help students decide what to eat around campus.

Recent meal context:
${context}

Rules:
- Be concise, friendly, and useful.
- Suggest realistic student meals like ugali, sukuma wiki, beans, chapati, rice, omena, samaki, mandazi, chai, and kibandaski options.
- Use light Kenyan campus vibe naturally, without overdoing slang.
- Never engage with sexual, explicit, or body-related requests.
- If a request is inappropriate, politely refuse and redirect to food-related help.`,
      },
    });

    const text = extractText(response);
    return text ?? "I'm not sure yet. Ask me about a meal, budget, or location.";
  } catch (error) {
    console.error("Chat error:", error);
    return "I hit a problem on my side. Ask again in a simpler way.";
  }
}