import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export async function generateMealImage(mealCombo: string): Promise<string> {
  // Client-side check for restricted content
  const restrictedWords = ["sex", "porn", "naked", "nude", "penis", "vagina", "breast", "ass", "butt", "pussy"];
  const lowerMeal = mealCombo.toLowerCase();
  if (restrictedWords.some(word => lowerMeal.includes(word))) {
    throw new Error("INAPPROPRIATE_CONTENT");
  }

  try {
    // Use user API key if available for higher quality models
    const imageAi = new GoogleGenAI({ apiKey: process.env.API_KEY || process.env.GEMINI_API_KEY || "" });
    
    const response = await imageAi.models.generateContent({
      model: "gemini-3.1-flash-image-preview",
      contents: {
        parts: [
          {
            text: `A professional food photography shot of a Kenyan meal combo: ${mealCombo}. 
            The meal is served on a clean plate, placed on a wooden table. 
            Cinematic lighting, vibrant colors, close-up shot. 
            NO PEOPLE, NO HANDS, NO FACES.`,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("No image generated by the model");
    }

    const parts = response.candidates[0].content?.parts || [];
    for (const part of parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by the model");
  } catch (error: any) {
    console.error("Error generating image:", error);
    
    // If it's a safety error, throw specific error
    if (error.message?.includes("SAFETY")) {
      throw new Error("INAPPROPRIATE_CONTENT");
    }

    // Fallback to a food-specific placeholder if image generation fails
    return `https://loremflickr.com/800/800/food,meal,kenyan?lock=${encodeURIComponent(mealCombo)}`;
  }
}

export async function generateMealVideo(mealCombo: string): Promise<string> {
  // Client-side check for restricted content
  const restrictedWords = ["sex", "porn", "naked", "nude", "penis", "vagina", "breast", "ass", "butt", "pussy"];
  const lowerMeal = mealCombo.toLowerCase();
  if (restrictedWords.some(word => lowerMeal.includes(word))) {
    throw new Error("INAPPROPRIATE_CONTENT");
  }

  try {
    // Create a fresh instance for video generation to use the user-selected API key
    const videoAi = new GoogleGenAI({ apiKey: process.env.API_KEY || process.env.GEMINI_API_KEY || "" });
    
    let operation: any = await (videoAi.models as any).generateVideos({
      model: 'veo-3.1-lite-generate-preview',
      prompt: `A high-quality, professional food cinematography video of a Kenyan meal combo: ${mealCombo}. The camera should slowly pan over the steaming hot food, showing the textures of the meal. NO PEOPLE, NO FACES. Cinematic lighting, 1080p, vibrant colors.`,
      config: {
        numberOfVideos: 1,
        resolution: '1080p',
        aspectRatio: '1:1'
      }
    });

    // Poll for completion
    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 10000));
      operation = await (videoAi.operations as any).get(operation.name);
    }

    if (operation.response?.generatedVideos?.[0]?.video?.uri) {
      return operation.response.generatedVideos[0].video.uri;
    }
    
    throw new Error("No video generated by the model");
  } catch (error) {
    console.error("Error generating video:", error);
    throw error;
  }
}

export async function generateProfileAvatar(fullname: string): Promise<string> {
  try {
    const avatarAi = new GoogleGenAI({ apiKey: process.env.API_KEY || process.env.GEMINI_API_KEY || "" });
    
    const response = await avatarAi.models.generateContent({
      model: "gemini-3.1-flash-image-preview",
      contents: {
        parts: [
          {
            text: `A professional, clean, and friendly student avatar for a person named ${fullname}. The style should be like a modern 3D illustration or a high-quality professional headshot. Neutral background, well-lit, suitable for a university profile.`,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("No avatar generated by the model");
    }

    const parts = response.candidates[0].content?.parts || [];
    for (const part of parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No avatar generated by the model");
  } catch (error) {
    console.error("Error generating avatar:", error);
    return `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(fullname)}`;
  }
}

export async function chatWithAssistant(message: string, context: string): Promise<string> {
  // Client-side check for restricted content
  const restrictedWords = ["sex", "porn", "naked", "nude", "penis", "vagina", "breast", "ass", "butt", "pussy"];
  const lowerMessage = message.toLowerCase();
  if (restrictedWords.some(word => lowerMessage.includes(word))) {
    return "INAPPROPRIATE_CONTENT_DETECTED";
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: message,
      config: {
        systemInstruction: `You are the Ulikula? Assistant for MMUST (Masinde Muliro University of Science and Technology) students. 
        Your goal is to help students decide what to eat. 
        Current context of recent posts: ${context}.
        Be friendly, use student slang where appropriate (e.g., 'kibandaski', 'comrades'), and suggest meal combos based on the context or general student favorites like Ugali, Sukuma, Chapati, Beans, etc.
        
        STRICT SAFETY RULE: You are strictly forbidden from generating, responding to, or acknowledging any sexual content, body parts, or inappropriate language. If a user asks for such content, politely decline and remind them that this is a student food community.
        
        Keep responses concise and helpful.`,
      },
    });
    return response.text || "I'm not sure what to say. Maybe try asking about specific meals?";
  } catch (error) {
    console.error("Chat error:", error);
    return "I'm having a bit of a brain freeze. Can you ask that again?";
  }
}
